### ISSUE TITLE
Stremio Universal Hebrew Subtitles

### ISSUE THREAD

**Issue by TwilightMercy** [Nitzantomer1998/CampExplorer#1]
Hi,

Sorry for opening the issue here (I wanted to reach you through your [Wizdom's fork](https://github.com/Nitzantomer1998/wizdom-stremio-v2), but issues are closed)

Continuing my question on your issue at Maor's wizdom repo,

Good job on making one universal addon for Hebrew subtitles!
https://stremio-addons.netlify.app/universal-hebrew-subtitles

I am working on same addon through Kodi, and I think we have a lot to discuss about : ) I want to contribute to your development process.

![image](https://github.com/Nitzantomer1998/CampExplorer/assets/29895680/6af7adbd-5c4f-4cb3-a942-87e7bb3cb5da)

------------------------------------------------------------------------------------------------------------------

Do you have telegram so we can talk privately? 

Twilight

**Comment by Nitzantomer1998** [comment]
Firstly, thank you for the recognition!

Right now, I'm in a good place with the project. I've completed the integration with Wizdom, which is currently the most optimal source for subtitles. I've also finished the integration with OpenSubtitles, but I haven't pushed it yet because I'm working on implementing a feature that allows users to choose their preferred subtitle sources.

Once I've finished the configuration for selecting website providers, I will publish the repository publicly. At that point, feel free to contribute. If you have any questions or suggestions, feel free to reach out to me via email (Nitzantomer1998@gmail.com).

**Comment by TwilightMercy** [comment]
Thank you for the quick reply, and good luck with your exams!

I wanna say thank you again for starting this project, because for a long time Stremio users seek for a universal Hebrew subtitles addon (similar to Kodi) that can manage all the match sorting / addon configuration all at once. So it's great. 

I briefly tested the addon from my PC and it works good. I have few questions:

1. First thing I've noticed is the subtitle name itself appears in the Sub ID label, does/will it help in terms of matching the subtitle to the current playing video file name?

![image](https://github.com/Nitzantomer1998/CampExplorer/assets/29895680/6a84ae4e-2b5e-4ec6-8bdb-0faf62ffc806)


2. Regarding OpenSubtitles.com API, do you plan to add user's personal API key configuration from OpenSubtitles, or come with default API keys for usage?

3. I agree that Wizdom is amazing Israeli subtitles source, and very easy API to implement. Do you plan to also Add Ktuvit website as a source
Similar to Maor's Ktuvit addon:
https://github.com/maormagori/ktuvit-stremio
https://4b139a4b7f94-ktuvit-stremio.baby-beamup.club/


Once you'll publish the repository public, I will be happy to reach you privately through mail (I run big Israeli Kodi/Stremio Telegram community (3K-4K members each griypy) for helping using the apps and install the rights addons, so I can help with announcing there the addon if you want)

Twilight

**Comment by Nitzantomer1998** [comment]
Thank you for your enthusiasm! I've made the addon [repository](https://github.com/Nitzantomer1998/UniversalHebrewSubtitlesAddon) public, and it currently only supports Wizdom (Because i didn't run OpenSubtitles tests). Please feel free to open issues there for any questions or discussions. I'll respond to all your queries promptly.

Let's keep this conversation focused on related details. If you have any unrelated questions or issues, please open an issue on the addon [repository](https://github.com/Nitzantomer1998/UniversalHebrewSubtitlesAddon), and we can discuss them there.

Looking forward to your contributions!

**Comment by TwilightMercy** [comment]
Congratulations on making the repository public :)
If that's ok, I'll soon open there separate issues to some of my suggestions:)
